[[facts]]
id = 1
fact = "En katt kan være høyre eller venstre-potet"

[[facts]]
id = 2
fact = "En katt kan hoppe opp til syv ganger sin egen høyde"

[[facts]]
id = 3
fact = "En katt kan løpe nesten 50 kilometer i timen - hvis den vil"

[[facts]]
id = 4
fact = "En katt kan se omkring seks ganger bedre enn mennesker om natten"

[[facts]]
id = 5
fact = "En katt har ingen svettekjertler"

[[facts]]
id = 6
fact = "En katt vil i gjennomsnitt bruke 30% av sitt liv på å rengjøre seg selv"

[[facts]]
id = 7
fact = "En katts hjerne ligner mer en menneskes hjerne, enn en hunds hjerne"

[[facts]]
id = 8
fact = "En katts hørsel er en av de beste i hele dyreriket"

[[facts]]
id = 9
fact = "Katter kan høre lyder så høye som 65 kHz, et menneskes hørsel stopper ved 20 kHz"

[[facts]]
id = 10
fact = "En katts hjerte slår 110 til 140 slag i minuttet, dobbelt så hurtig som et menneskes hjerte"

[[facts]]
id = 11
fact = "Overtroen om at sorte katter betyr uhell har opprinnelse i Amerika. I Asia og England er sorte katter et tegn på hell"

[[facts]]
id = 12
fact = "Både mennesker og katter har identiske regioner i hjernen som er ansvarlige for følelseslivet"

[[facts]]
id = 13
fact = "Katte sover i gjennomsnitt 16 timer i døgnet, lengre enn noe annet pattedyr"

[[facts]]
id = 14
fact = "Katten kan lære å utføre tricks."

[[facts]]
id = 15
fact = "Katten kan se farger. Undersøkelser viser at katter kan skille mellom rød og grønn, rød og blå, rød og grå, grønn og blå, grønn og grå, blå og grønn, gul og blå og gul og grå"

[[facts]]
id = 16
fact = "Katten har AB blodtyper, ganske like mennesker"

[[facts]]
id = 17
fact = "Katten har omkring 100 forskjellige vokaliseringslyder. Til sammenligning har hunden ca. 10"

[[facts]]
id = 18
fact = "Katten skal ha fett i kosten fordi de ikke kan produsere det selv. Gi aldri katten din hundefor, da katten har bruk for fem ganger så mye protein som en hund"

[[facts]]
id = 19
fact = "Katter kan ikke overleve på en vegetarisk kost"

[[facts]]
id = 20
fact = "Sjokolade er giftig for katter"

[[facts]]
id = 21
fact = "I forhold til størrelsen på kroppen, er katter det pattedyr som har størst øyne"

[[facts]]
id = 22
fact = "Det var dødsstraff i det gamle Egypt for å slå en katt ihjel - også selv om det skjedde ved et uhell!"

[[facts]]
id = 23
fact = "Katter har 24 værhår"

[[facts]]
id = 24
fact = "Katter kan enkelt lese menneskets humør og ofte forandre sitt eget humør for å passe eierens"

[[facts]]
id = 25
fact = "Katter hilser på hverandre med å ta nese mot nese"

[[facts]]
id = 26
fact = "Katter kan bare bevege kjeven opp og ned og ikke til siden"

[[facts]]
id = 27
fact = "For lenge siden var det en katt som døde fordi den ble matet fire minutter for sent. Denne historien har gått i arv i mer enn 3000 generasjoner av katter"

[[facts]]
id = 28
fact = "Katter mister melketenner som oss mennesker"

[[facts]]
id = 29
fact = "Katter er det mest populære kjæledyret i USA: Det er 88 millioner kjæledyrkatter og 74 millioner hunder"

[[facts]]
id = 30
fact = "Katter sover 70 % av livet sitt"

[[facts]]
id = 31
fact = "Katter kan drikke sjøvann for å overleve"

[[facts]]
id = 32
fact = "Katter kan rotere ørene sine 180 grader"

[[facts]]
id = 33
fact = "En katts hjerte slår dobbelt så raskt som et menneskes, rundt 110 til 140 slag per minutt"

[[facts]]
id = 34
fact = "Katter har fem tær på frempotene, men bare fire på bakpotene"
